title: "Dr. Lars E.O. Jacobson"
description: "Computer Science description"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"   # try "default", "contrast", "dark"

author:
  name: "Dr. Lars E.O. Jacobson"
  avatar: "/assets/img/profile.jpg"
  bio: "Computer Science bio"
  location: "London, United Kingdom"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:lars@eojacobson.com"
    - label: "ORCID"
      icon: "fas fa-id-badge"
      url: "https://orcid.org/0009-0003-0582-7576"
    - label: "ResearchGate"
      icon: "fas fa-project-diagram"   # or "fas fa-flask"
      url: "https://www.researchgate.net/profile/Lars-Erik-Olof-Jacobson?ev=hdr_xprf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/larsjacobson"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/lars-e-o-jacobson-748a3077"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=MAJxrGcAAAAJ&hl=en&oi=ao"

logo: /assets/img/logo.png
favicon: /assets/img/favicon.png

collections:
  pages:
    output: true
    permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: references.bib

sass:
  sass_dir: _sass
  style: compressed

footer:
  links:
    - label: "Contact"
      url: "/about/"
    - label: "GitHub"
      url: "https://github.com/larseojacobson"
  
copyright: "© 2025 Dr. Lars E. O. Jacobson. All rights reserved."

url: "https://larseojacobson.com"
baseurl: ""