source "https://rubygems.org"
ruby ">= 3.1.0"

gem "jekyll", "~> 4.3.3"
gem "minimal-mistakes-jekyll", "~> 4.26"
gem "jekyll-scholar", "~> 7.1"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-include-cache"
