source "https://rubygems.org"
ruby ">= 3.1.0"

gem "jekyll", "~> 4.3.3"
gem "webrick", "~> 1.8"
gem "jekyll-scholar", "~> 7.1"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-include-cache", "~> 0.2"
gem "minimal-mistakes-jekyll", "~> 4.26"
